<a href="https://colab.research.google.com/github/gg0099/CMPS-261-Project/blob/main/randomTrails.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing the libraries
import numpy as np
import pandas as pd
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
# Importing the dataset
dataset = pd.read_csv('data.csv')

In [ ]:
# Cleaning the texts
corpus = []
for i in range(len(dataset)):
  text = re.sub('[^a-zA-Z]', ' ', dataset['medical_abstract'][i])
  text = text.lower()
  text = text.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
  text = ' '.join(text)
  corpus.append(text)

In [ ]:
print(corpus[0])

tissu chang around loos prosthes canin model investig effect antiinflammatori agent asept loosen prosthesi provid mean investig vivo vitro activ cell associ loosen process seven dog cell isol maintain cultur suffici period time biolog activ could studi well effect differ agent ad cell vivo vitro biolog respons determin interleukin prostaglandin e activ parallel roentgenograph appear loosen technetium imag observ made time revis surgeri correl clinic roentgenograph histolog biochem loosen indic canin model suitabl investig mechan prosthet failur canin model permit studi possibl nonsurg therapeut intervent ultim hope stop slow loosen process


In [ ]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset['condition_label'].values

In [ ]:
# Creating the TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=1500)
X = tfidf.fit_transform(corpus).toarray()
y = dataset['condition_label'].values  # Assuming the label is in this column

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
# Training the model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, max_iter=1000)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear', random_state=0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
# Evaluating the results
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print('Accuracy:', accuracy)

[[373  16  23  13  84]
 [ 26 124   6   4  94]
 [ 21   1 145  24 125]
 [ 15   8  15 344  77]
 [ 90  57  71 139 415]]
Accuracy: 0.6064935064935065


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
# Using unigrams and bigrams
cv = CountVectorizer(max_features=1500, ngram_range=(1, 2))
X = cv.fit_transform(corpus).toarray()


In [ ]:
from sklearn.model_selection import GridSearchCV
# Define the grid of parameters
param_grid = {'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf']}
# Initialize GridSearchCV
grid_search = GridSearchCV(SVC(random_state=0), param_grid, cv=5, n_jobs=-1)
# Fit the grid search to the data
grid_search.fit(X_train, y_train)
# Get the best parameters
best_params = grid_search.best_params_
print("Best Parameters:", best_params)
# Use the best parameters to create the final model
classifier = SVC(**best_params, probability=True, random_state=0)
classifier.fit(X_train, y_train)


/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()
/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()


Best Parameters: {'C': 1, 'kernel': 'linear'}


SVC(C=1, kernel='linear', probability=True, random_state=0)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
# Initialize Gradient Boosting classifier
gb_classifier = GradientBoostingClassifier(n_estimators=100, random_state=0)
# Fit the classifier to the training data
gb_classifier.fit(X_train, y_train)
# Predict the test set results
y_pred_gb = gb_classifier.predict(X_test)
# Evaluate the results
accuracy_gb = accuracy_score(y_test, y_pred_gb)
print("Gradient Boosting Accuracy:", accuracy_gb)


Gradient Boosting Accuracy: 0.5705627705627706


In [ ]:
from sklearn.ensemble import RandomForestClassifier
# Initialize Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=0)
# Fit the classifier to the training data
rf_classifier.fit(X_train, y_train)
# Predict the test set results
y_pred_rf = rf_classifier.predict(X_test)
# Evaluate the results
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)


Random Forest Accuracy: 0.5008658008658009


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Importing the libraries
import numpy as np
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from keras.models import Sequential
from keras.layers import Dense

# Ensure stopwords are downloaded
nltk.download('stopwords')

# Importing the dataset
dataset = pd.read_csv('data.csv')  # Update the filename and format if necessary

# Cleaning the texts
corpus = []
for i in range(len(dataset)):
  text = re.sub('[^a-zA-Z]', ' ', dataset['medical_abstract'][i])
  text = text.lower()
  text = text.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
  text = ' '.join(text)
  corpus.append(text)

# Creating the TF-IDF model
tfidf = TfidfVectorizer(max_features=1500)
X = tfidf.fit_transform(corpus).toarray()
y = dataset['condition_label'].values - 1  # Make sure your labels are appropriately encoded as integers

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Building the Neural Network
model = Sequential()
model.add(Dense(512, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(256, activation='relu'))
model.add(Dense(5, activation='softmax'))  # Use softmax for multi-class classification

# Compiling the Neural Network
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Training the Neural Network
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Evaluating the model on the test data
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy: {:.2f}%".format(accuracy * 100))

# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)  # Convert predictions to one-hot encoding to class labels

# Confusion Matrix and Classification Report
cm = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:")
print(cm)

# Classification report
cr = classification_report(y_test, y_pred_classes)
print("Classification Report:")
print(cr)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Epoch 1/10
289/289 [==============================] - 6s 16ms/step - loss: 1.0677 - accuracy: 0.5558 - val_loss: 0.9670 - val_accuracy: 0.5870
Epoch 2/10
289/289 [==============================] - 4s 12ms/step - loss: 0.7853 - accuracy: 0.6646 - val_loss: 0.9777 - val_accuracy: 0.5848
Epoch 3/10
289/289 [==============================] - 4s 16ms/step - loss: 0.6635 - accuracy: 0.7009 - val_loss: 1.0334 - val_accuracy: 0.5632
Epoch 4/10
289/289 [==============================] - 3s 12ms/step - loss: 0.5612 - accuracy: 0.7420 - val_loss: 1.1440 - val_accuracy: 0.5494
Epoch 5/10
289/289 [==============================] - 4s 14ms/step - loss: 0.4782 - accuracy: 0.7590 - val_loss: 1.2952 - val_accuracy: 0.5320
Epoch 6/10
289/289 [==============================] - 5s 17ms/step - loss: 0.4173 - accuracy: 0.7728 - val_loss: 1.4539 - val_accuracy: 0.5208
Epoch 7/10
289/289 [==============================] - 3s 12ms/step - loss: 0.3660 - accuracy: 0.7868 - val_loss: 1.5920 - val_accuracy: 0.5052

In [ ]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.regularizers import l2
from keras.callbacks import EarlyStopping

# Ensure necessary NLTK resources are downloaded
nltk.download('punkt')  # Tokenizer model
nltk.download('stopwords')
nltk.download('wordnet')

# Load the dataset
dataset = pd.read_csv('data.csv')  # Ensure you have a correct path

# Preprocess the dataset
def preprocess_text(text):
    text = re.sub(r"[^\w\s]", "", text.lower())
    tokens = nltk.word_tokenize(text)  # Uses punkt
    tokens = [word for word in tokens if word not in stopwords.words('english')]
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(tokens)

# Apply preprocessing to the medical_abstract column
dataset['processed_text'] = dataset['medical_abstract'].apply(preprocess_text)

# Vectorization
tfidf_vectorizer = TfidfVectorizer(max_features=1500)
X = tfidf_vectorizer.fit_transform(dataset['processed_text']).toarray()
y = dataset['condition_label'].values - 1  # Adjust labels to start from 0

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

# Building the model with dropout and L2 regularization
model = Sequential([
    Dense(512, activation='relu', input_dim=X_train.shape[1], kernel_regularizer=l2(0.01)),
    Dropout(0.5),
    Dense(256, activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.5),
    Dense(5, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Setting up Early Stopping
early_stopping_monitor = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

# Training the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32,
                    validation_data=(X_test, y_test), callbacks=[early_stopping_monitor])

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy * 100:.2f}%")


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Epoch 1/10
289/289 [==============================] - 6s 18ms/step - loss: 2.2520 - accuracy: 0.4512 - val_loss: 1.4667 - val_accuracy: 0.5273
Epoch 2/10
289/289 [==============================] - 4s 13ms/step - loss: 1.4464 - accuracy: 0.5300 - val_loss: 1.4463 - val_accuracy: 0.5203
Epoch 3/10
289/289 [==============================] - 4s 14ms/step - loss: 1.4208 - accuracy: 0.5287 - val_loss: 1.4271 - val_accuracy: 0.5264
Epoch 4/10
289/289 [==============================] - 5s 17ms/step - loss: 1.3981 - accuracy: 0.5304 - val_loss: 1.3953 - val_accuracy: 0.5087
Epoch 5/10
289/289 [==============================] - 4s 13ms/step - loss: 1.3910 - accuracy: 0.5316 - val_loss: 1.3908 - val_accuracy: 0.5247
Epoch 6/10
289/289 [==============================] - 4s 13ms/step - loss: 1.3738 - accuracy: 0.5374 - val_loss: 1.3782 - val_accuracy: 0.5320
Epoch 7/10
289/289 [==============================] - 5s 17ms/step - loss: 1.3684 - accuracy: 0.5346 - val_loss: 1.3756 - val_accuracy: 0.5247